# Generated by Django 5.0.3 on 2024-03-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(db_column='customer_ID', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=256)),
                ('customer_mobile', models.BigIntegerField()),
                ('customer_password', models.CharField(max_length=24)),
                ('account_type', models.IntegerField(db_column='Account_type', db_comment='1 = Free\r\n2 = Premium')),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
    ]
